### ISSUE TITLE
Script won't run when Netplay Community Settings exist in Dolphin

### ISSUE THREAD

**Issue by someone2639** [altf4/SmashBot#102]
Here's the traceback when I try to run the code:

Traceback (most recent call last):
  File "./smashbot.py", line 54, in <module>
    opponent_type=opponent_type, logger=log)
  File "/usr/local/lib/python3.5/dist-packages/melee/dolphin.py", line 41, in __init__
    self.setup_controller(ai_port)
  File "/usr/local/lib/python3.5/dist-packages/melee/dolphin.py", line 111, in setup_controller
    config.read(melee_config_path)
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/someone2639/.local/share/dolphin-emu//GameSettings/GALE01.ini' [line 41]: option '8A830678 3DC08000' in section 'Gecko' already exists

**Comment by altf4** [comment]
Could you paste the contents of:

/home/someone2639/.local/share/dolphin-emu//GameSettings/GALE01.ini

Looks like libmelee is having a hard time parsing it.

**Comment by someone2639** [comment]
It's a bit long but it should be pretty much the same as [this file](https://github.com/dolphin-emu/dolphin/blob/master/Data/Sys/GameSettings/GALE01r2.ini)
```
[ActionReplay]
$Items Off
0045C370 000000FF
$Game Mode Stock
0045BF12 00000001
$4 Stocks
0045BF14 00000004
$Stock Match Time Limit 8 Mins
0045BF18 00000008
$Boot to Character Select [Dan Salvato]
041A45A0 3C000202
041A45A4 901E0000
$Debug Menu
0422D638 38000006
$C Stick in Single Player [Zauron]
0416B480 60000000
$Disable Peach's Castle Bullets [Zauron]
041CD8A8 4E800020
$Disable Brinstar's Rising Lava [Zauron]
041D99E0 4E800020
$Disable Dreamland's Wind [Zauron]
04211444 60000000
$Disable Platforms on FoD [Zauron]
041CC8AC FC000028
041CC8B4 4800013C
$Disable Corneria's Arwings [Zauron]
041DDA48 60000000
$No Great Fox Guns [Zauron]
041E1390 40800430
$Disable Green Greens Blocks [Zauron]
042146EC 60000000
04216B24 60000000
$Disable Green Greens Tree Stuff [Zauron]
04213C10 4E800020
$Disable Pokemon Stadium Transformations [Zauron]
041D1548 60000000
$Disable Yoshi's Story Shyguys [Zauron]
041E3348 60000000
$Disable Special Messages [NMN]
04173EEC 4E800020
0415D8E0 4E800020
04005778 4E800020
0415D934 38000000
0415D9BC 38600000
04005780 48000014
042FE918 4E800020
$Flash on L Cancel [Dan Salvato]
0408D6A0 48519A60
045A7100 C00600E8
045A7104 39E000D4
045A7108 99E30564
045A710C 4BAE6598
040C0148 484E6FC8
045A7110 387F0488
045A7114 89FE0564
045A7118 2C0F00D4
045A711C 41820008
045A7120 4BB1902C
045A7124 39E00091
045A7128 99FE0564
045A712C 3DE0C200
045A7130 91FE0518
045A7134 91FE051C
045A7138 91FE0520
045A713C 91FE0524
045A7140 3DE0C280
045A7144 91FE0534
045A7148 4BB19008
$Input Delay Tester [Dan Salvato]
3C608047 60639C3C
80630000 3C80805A
60847D00 3CA080BD
60A5A4A0 80050000
2C000000 418200DC
80A50000 546007BD
408200B4 54600739
408200B8 80040000
2C000000 418200BC
38C00000 90C50564
80E40004 2C070000
41820054 48000004
5460077B 40820008
48000024 7CE83B78
2C080014 41800008
39000000 3CC08045
60C630E0 B1060000
48000004 38E70001
2C07001E 4080000C
90E40004 48000064
38E00000 90E40004
48000058 3CC0437F
90C50518 90C50524
38C00000 90C5051C
90C50520 90C50528
90C5052C 90C50530
90C50534 3CC08000
60C60091 90C50564
4BFFFF80 38000001
90040000 4BFFFF5C
38000000 90040000
90040004 48000004
7C0802A6 00000000
$Widescreen Support v1.2 [Dan Salvato]
04BDC5E4 3FCFC217
$Tournament Stages Only for Random
0445C388 47000090
$Tournament Stages Only for Random Full
0445C388 47000030
$True Special Message Delete [JMC47]
0445C20C 39400000
0245C390 00030000
0445C0D4 01010100
0045C110 00000001
0445C230 10000000
0045C114 00000027
0445C228 80000000
0045C22C 00001111
[Gecko]
$Netplay Community Settings
0445BF28 FFFFFFFF
0445BF2C FFFFFFFF
0415d94c 4e800020
041a45a0 3c000202
041a45a4 901e0000
C21BFA20 00000003
3DE08017 61EF2898
7DE903A6 4E800421
38600002 00000000
0424cec4 48000058
04162ee8 60000000
0245C390 00000125
0245C395 01266363
041644E8 38600001
041648F4 38600001
04164F34 38600001
043D4A48 00340102
043D4A4C 04000A00
043D4A50 08010100
043D4A60 FF000000
043D4A78 E70000B0
0415d984 4e800020
0425b8bc 38600002
04261B1C 60000000
04261B30 60000000
041A55EC 4E800020
C208D600 00000009
8A830678 3DC08000
61CE45D4 1EB40008
7DCEAA14 81EE0000
39EF0001 91EE0000
3A0EFFFC 82300000
7E717BD6 3E408045
62523DA4 1EB40E90
7E52AA14 92720000
3880FFFF 00000000
C208D6A4 00000009
8A830678 3DC08000
61CE45D4 1EB40008
7DCEAA14 81EE0000
3A0EFFFC 82300000
3A310064 92300000
7E717BD6 3E408045
62523DA4 1EB40E90
7E52AA14 92720000
EC010024 00000000
04040BBC 60000000
20C61DB8 16200D20
06C61DB8 00000014
1620151A 200C2024
20312026 2028202F
1A210300 00000000
020045D0 000F0000
E2000001 00000000
C2259C40 0000001F
39600000 3D408045
614AC388 38600000
3C80803F 608406D0
28000013 4082000C
39600001 48000010
28000000 408200C0
48000034 2C03001D
408000B4 2C0B0002
4182004C 1CA3001C
7CA52214 88C5000A
80AA0000 7CA53430
54A507FF 40820088
4800002C 806DB600
5460056B 4082001C
546006F7 40820008
48000074 39600002
38600000 4BFFFFB0
886DB60E 2C03001D
4080005C 1CA3001C
7CA52214 38C00000
2C0B0002 40820008
38C00002 98C50008
80A50000 2C030016
41800008 80A50010
3CC04400 2C0B0002
40820008 38C00000
90C50038 38C0001E
98CDB60E 2C0B0000
4182000C 38630001
4BFFFF4C 800DB604
28000000 00000000
C216E2DC 00000017
3C608000 60633300
3C80804D 88846CAE
38C00000 7CA6182E
7C052000 41820014
2C05FFFF 4182000C
38C6000C 4BFFFFE8
38C60004 3CE08048
88E707C8 2C070000
41820008 38C60004
7CA6182E 90A3FFFC
4182005C 39000000
3C80803F 60840E06
80E40000 39080001
2C080004 40800040
1D280024 7CC9202E
7C063800 4082FFE8
3863FFFC 7D064378
38C6FFFF 2C060000
4081001C 7C8618AE
7CA818AE 7CA619AE
7C8819AE 3908FFFF
4BFFFFE0 881F0007
60000000 00000000
C216E48C 00000004
3CA08000 60A532FC
8085FFFC 7C6428AE
38840001 9085FFFC
60000000 00000000
C216DF54 00000004
3CA08000 60A532FC
8085FFFC 7C6428AE
38840001 9085FFFC
60000000 00000000
C216DF30 00000003
3C808000 608432F8
38A00000 90A40000
3B9A0000 00000000
C216E468 00000003
3C808000 608432F8
38A00000 90A40000
3F600004 00000000
06003300 00000060
00000019 00010203
00020103 00000008
00010203 02000301
00000006 00010302
03000201 0000001a
01030002 00010203
00000018 02030001
00020103 00000012
03020001 03000201
0000001c 00030102
00010302 ffffffff
00010203 00010203
0416B480 60000000
C21A4160 00000008
39C00000 3DE08046
61EFB108 820F0000
5611018D 41820010
561101CF 41820008
38000002 39CE0001
2C0E0004 4080000C
39EF000C 4BFFFFD8
981F0003 00000000
04452F54 42000000
04452F58 42000000
04452F5C 42000000
04452F60 40200000
04452F64 47000000
0406AE90 38000000
040300A4 38000000
0422D638 38000006
043FA25B 01000000
041b0a14 38600002
224d6c94 00000000
04c8ee24 00000000
04c8ea04 99b3b3ff
04c79964 ccccccff
04c73758 ffffffff
04cb1a88 80ca3570
04cb1aa8 80ca3574
04ca3578 00000000
04ca357c c0000077
28469d44 00000001
04c8ee24 3f490fdb
04c8ea04 5060ffff
04c79964 6060ffff
04c73758 9090ffff
04cb1a88 80ca3578
04cb1aa8 80ca357c
04ca3578 0000ff00
04ca357c 0000ff00
82000000 80ca3571
84000000 80ca3578
84000000 80ca3579
84000000 80ca357c
84000000 80ca357d
e2000002 00000000
C21D4548 00000003
3C808047 A0849D44
2C040001 4D820020
7C0802A6 00000000
C22115AC 00000004
801F00D0 3C808047
A0849D44 2C040001
40820008 38000001
60000000 00000000
C21E3418 00000003
3C808047 A0849D44
2C040001 4D820020
7C0802A6 00000000
C221B2E8 00000003
3C808047 A0849D44
2C040001 4D820020
7C0802A6 00000000
C220f52c 00000003
3C808047 A0849D44
2C040001 4D820020
7C0802A6 00000000
C2259C48 0000000A
806DB600 54600529
41820040 A01F0002
2C000001 40820034
38600001 3D808002
618C4030 7D8903A6
4E800421 3E608046
62739D45 8A930000
6A940001 9A930000
3A80001E 9A8DB60E
886DB60E 00000000
C21A4DA0 00000003
901C0000 3D808001
618C95FC 7D8903A6
4E800421 00000000
08402cc4 004e0400
20020004 00000000
04019860 4bfffd9d
*Boot to CSS, unlock everything, 4 stock 8 minute friendly fire on, trophy messages off,
*L+R+Start during stage load returns to CSS, name tags don't reset on close or exit,
*L-cancel % on results screen, normal C Stick functionality in 1P modes,
*Stage striking, A+B salty runback, unrestricted pause camera,
*Normal C Stick functionality in develop mode, debug menu access and set to English,
*leaving debug menu loads CSS, neutral spawn points,
*Increase input timing accuracy, press Y to toggle frozen stages
$Netplay Safe Kill Music [Dan Salvato, Summate]
040249a4 38600001
$Unlock All Characters and Stages [Datel]
0445BF28 FFFFFFFF
0445BF2C FFFFFFFF
*Also Unlocks All Star Mode, Sound Test, and Vs. Mode Additions
$Unlock All 293 Trophies [Datel]
0245C390 00000125
0245C395 01266363
$Default Tournament Settings [Magus, et all]
043D4A48 00340102
043D4A4C 04000A00
043D4A50 08010100
043D4A60 FF000000
043D4A70 00000000
043D4A74 3C000000
043D4A78 E70000B0
*4 stock, 8 min, items off, tourney legal stages,
*friendly fire on, rumble off for all players, sfx>music, deflicker off
$Boot to Character Select Screen [Dan Salvato, Achilles]
041BFA20 38600002
*Memory card data is loaded.
$Debug Menu Replaces Tournament Mode [Magus, donny2112]
0422D638 38000006
$Increase Input Timing Accuracy [Dan Salvato]
C21A4DA0 00000003
901C0000 3D808001
618C95FC 7D8903A6
4E800421 00000000
08402cc4 004e0400
20020004 00000000
04019860 4bfffd9d
*Reorganizes input polls to remove drift that causes occasional input lag.
*Also doubles the controller's poll rate.
$Disable Name Tag Reset After Closing Character Port [Ato]
04261B1C 60000000
04261B30 60000000
$Disable Name Tag Reset After Exiting Character Select Screen [Todd Bonney]
041A55EC 4E800020
$Zelda is Permanently Sheik at CSS [Achilles]
043F0CC8 12130200
*Selecting Zelda will have the player start the match as Sheik.
$Spoof Controller Plugins [Dan Salvato]
04260508 38000003
04261adc 38600000
*Lets you select HMN for slots that don't have a controller plugged in.
$Stage Striking [Sham Rock, Dan Salvato]
C2259C40 0000001F
39600000 3D408045
614AC388 38600000
3C80803F 608406D0
28000013 4082000C
39600001 48000010
28000000 408200C0
48000034 2C03001D
408000B4 2C0B0002
4182004C 1CA3001C
7CA52214 88C5000A
80AA0000 7CA53430
54A507FF 40820088
4800002C 806DB600
5460056B 4082001C
546006F7 40820008
48000074 39600002
38600000 4BFFFFB0
886DB60E 2C03001D
4080005C 1CA3001C
7CA52214 38C00000
2C0B0002 40820008
38C00002 98C50008
80A50000 2C030016
41800008 80A50010
3CC04400 2C0B0002
40820008 38C00000
90C50038 38C0001E
98CDB60E 2C0B0000
4182000C 38630001
4BFFFF4C 800DB604
28000000 00000000
**Stages disabled in Random Stage Select are struck automatically.
**X = ban currently selected stage
**Z = unban all
**Banned stages can't be selected anymore, however they can still be selected when someone chooses "Random".
$Press Y to toggle frozen stages [Dan Salvato]
224d6c94 00000000
04c8ee24 00000000
04c8ea04 99b3b3ff
04c79964 ccccccff
04c73758 ffffffff
04cb1a88 80ca3570
04cb1aa8 80ca3574
04ca3578 00000000
04ca357c c0000077
28469d44 00000001
04c8ee24 3f490fdb
04c8ea04 5060ffff
04c79964 6060ffff
04c73758 9090ffff
04cb1a88 80ca3578
04cb1aa8 80ca357c
04ca3578 0000ff00
04ca357c 0000ff00
82000000 80ca3571
84000000 80ca3578
84000000 80ca3579
84000000 80ca357c
84000000 80ca357d
e2000002 00000000
C21D4548 00000003
3C808047 A0849D44
2C040001 4D820020
7C0802A6 00000000
C22115AC 00000004
801F00D0 3C808047
A0849D44 2C040001
40820008 38000001
60000000 00000000
C21E3418 00000003
3C808047 A0849D44
2C040001 4D820020
7C0802A6 00000000
C221B2E8 00000003
3C808047 A0849D44
2C040001 4D820020
7C0802A6 00000000
C220f52c 00000003
3C808047 A0849D44
2C040001 4D820020
7C0802A6 00000000
C2259C48 0000000A
806DB600 54600529
41820040 A01F0002
2C000001 40820034
38600001 3D808002
618C4030 7D8903A6
4E800421 3E608046
62739D45 8A930000
6A940001 9A930000
3A80001E 9A8DB60E
886DB60E 00000000
*Press Y on the character select screen to enable frozen variants of tournament stages.
$"RANDOM" is Default Highlighted on Stage Select Screen [Jorgasms]
0425AA10 38E0001D
*As if you had already dragged the cursor over top of "Random" stage select.
$CSS Player Hands Default to HMN Button [Achilles]
044DC47C C0200000
$Extended Name Entry [Dan Salvato]
224D4CAC 20000000
044D4CAC 20000000
064D4D90 000000B4
4A000000 54000000
39000000 2E000000
49000000 53000000
38000000 81900000
48000000 52000000
37000000 81950000
47000000 51000000
36000000 81930000
46000000 50000000
5A000000 35000000
81970000 45000000
4F000000 59000000
34000000 81480000
44000000 4E000000
58000000 33000000
81490000 43000000
4D000000 57000000
32000000 81810000
42000000 4C000000
56000000 31000000
817B0000 41000000
4B000000 55000000
30000000 817C0000
E2000001 00000000
0423c710 28030007
0423c320 28030007
0423c6c4 28030007
0423cf74 60000000
0423cf9c 2c1b0008
C223E0A4 00000002
EC001028 C022C544
EC000824 00000000
C223C118 00000009
2C0A0000 4082003C
39400001 3CA0804A
38A5000C 38800198
3BDE0001 7C64F0AE
2C030000 4082FFF4
7C64F12E 7FC3F378
3D808023 618CC008
7D8903A6 4E800420
880D97AC 00000000
0423c12c 60000000
0623E9D4 00000014
38800000 7C04F9AE
38840003 2C040015
4081FFF4 00000000
0623e69c 00000014
38800000 7C04F1AE
38840003 2C040015
4081FFF4 00000000
C223CA28 00000005
2C0F0004 40800018
39EF0001 3D808023
618CC9EC 7D8903A6
4E800420 39E00000
38610024 00000000
C223C5A0 0000000F
5460056B 41820068
88BC0050 28050002
4082005C 3CA0804D
60A54D90 38C00000
2C0600B4 41810038
7CE628AE 2C070041
41800024 2C07007A
4181001C 2C070061
4180000C 38E7FFE0
48000008 38E70020
7CE629AE 38C60004
4BFFFFC8 3D808023
618CC7EC 7D8903A6
4E800420 546005AD
60000000 00000000
06238080 00000010
93E30198 93E3019C
93E301A0 93E301A4
*English alphabet name tags can be up to 8 characters in length.
*Press X Button to shift between upper and lowercase.
$Normal C Stick Functionality in Singleplayer Modes [Zauron]
0416B480 60000000
$Normal C Stick Functionality in Develop Mode [Magus, Achilles]
0406AE90 38000000
040300A4 38000000
*Does not work with Nana
$Skip Results Screen & Normal KO Star Count [Sham Rock, Achilles]
C21A415C 0000000E
3803FFFF 2C0B0020
41820064 2C000004
4082005C 3AC00000
3E608045 6273226F
3E40804D 6252672F
8E320001 8E930E84
7E31A214 8E930004
7E31A214 8E930004
7E31A214 8E930004
7E31A214 2C1100FF
41800008 3A2000FF
9A320000 3AD60001
2C160004 41A0FFC4
38000000 00000000
**Results Screen is skipped entirely
**KO Star Count functions normally
$Skip Results Screen & KO Stars Equals Games Won [Sham Rock, Achilles]
C21A415C 00000011
3803FFFF 2C0B0020
41820078 2C000004
40820070 3E208047
6231A1EC 7C088800
4082005C 3E00804D
3A9065A7 6210672F
3E208043 62312087
3A400000 3A520001
3A940001 3A100001
1E720008 7E738A14
8A730000 2C130021
4182001C 8AB40000
2C150000 40820010
8AB00000 3AB50001
9AB00000 2C120004
41A0FFC4 38000000
60000000 00000000
*Quitting will not earn any stars
$Skip Result Screen & KO Star Count Equals Placement [Sham Rock]
C21A415C 0000000E
3803FFFF 2C000004
40820060 2C0B0020
41820058 3A400000
3E808047 62949D58
3EA0804D 62B5672F
8E1400A8 8A340001
2C10004E 4080000C
9E350001 4800000C
3A310001 9E350001
3A520001 2C120004
41A0FFD8 3A000000
3A200000 3A800000
3AA00000 38000000
60000000 00000000
**KO Star Count displays player placement from the previous match
**1st Place = 1 Star
**2nd Place = 2 Stars
**etc.
$Hold A+B for Salty Runback [Dan Salvato]
C21A4160 00000008
39C00000 3DE08046
61EFB108 820F0000
5611018D 41820010
561101CF 41820008
38000002 39CE0001
2C0E0004 4080000C
39EF000C 4BFFFFD8
981F0003 00000000
*Hold A+B at the end of a match or during a ragequit
*and the match will be immediately restarted on the same stage
$Change Rumble Settings from CSS - Color Mod [Sham Rock]
C226304C 0000001F
8803000E 3DC08045
61CEC380 3DE08046
61EFB0FC 3A800000
860F000C 56110319
41820010 3A200001
9A2E0000 48000014
5611035B 4182000C
3A200000 9A2E0000
3A940001 39CE0001
2C140004 41A0FFCC
39CEFFFB 3E401919
62521900 3E00804C
2C140004 40820008
621024EC 2C140005
40820008 62102458
2C140006 40820008
62102558 2C140007
40820008 621024C4
2C140005 41810008
82100000 82100000
82100000 82100008
82100018 82100008
8210001C 82100004
82100008 8E2E0001
2C110001 40820010
3E20EEEE 6231EE00
4800000C 3E205555
62315500 92300000
92500004 3A940001
2C140008 41A0FF70
60000000 00000000
*Pressing Up/Down on the D-Pad while at the CSS in versus mode
*will set the Rumble settings for that slot to On/Off
*Colored CSP background is modified;
*White = Rumble On, Grey = Rumble Off
$L-Cancel Training Wheels [Dan Salvato]
C208D69C 00000002
4080000C 39E000D4
99E30564 00000000
C20C0148 0000000C
387F0488 89FE0564
2C0F00D4 41820008
48000048 39E00091
99FE0564 3DE0C200
91FE0518 91FE051C
91FE0520 91FE0524
3DE00000 91FE0528
91FE052C 91FE0530
3DE0C280 91FE0534
3DE0800C 61EF0150
7DE903A6 4E800420
60000000 00000000
*This code automatically L-cancels all aerials,
*but your character will flash white if your input was correct.
*This allows players to practice L-canceling
*but suffer no penalty if the L-cancel is missed,
*allowing the player to practice combos and mental game
*even without yet having mastered L-canceling.
$Aerials are Automatically L-Cancelled [Dan Salvato]
0406B620 60000000
$Flash White on Successful L-Cancel [Dan Salvato]
C208D6A0 00000002
C00600E8 39E000D4
99E30564 00000000
C20C0148 0000000C
387F0488 89FE0564
2C0F00D4 41820008
48000048 39E00091
99FE0564 3DE0C200
91FE0518 91FE051C
91FE0520 91FE0524
3DE00000 91FE0528
91FE052C 91FE0530
3DE0C280 91FE0534
3DE0800C 61EF0150
7DE903A6 4E800420
60000000 00000000
*Do not use with "Flash Red on Unsuccessful L-Cancel"
$Flash Red on Unsuccessful L-Cancel [Achilles,Dan Salvato]
C208D690 00000003
88A5067F 2C050007
4180000C 39E000D4
99E30564 00000000
C20C0148 0000000C
387F0488 89FE0564
2C0F00D4 41820008
4800004C 39E00091
99FE0564 3DE0437F
91FE0518 3DE0C200
91FE0524 3DE00000
91FE051C 91FE0520
91FE0528 91FE052C
91FE0530 3DE0C280
91FE0534 3DE0800C
61EF0150 7DE903A6
4E800420 00000000
*Do not use with "Flash White on Successful L-Cancel"
$Disable Tap Jump [Achilles]
C20CBBC0 00000003
89FD06BE 2C0F0004
40800008 4E800020
7C0802A6 00000000
C20CB4E0 00000003
2C040001 40820008
4E800020 7C0802A6
60000000 00000000
*Affects all players
$Costume Dependent Marth Sword Swing Colors [Achilles]
C2136510 0000000F
3DC0FF00 61CEFFFF
7C007000 40820060
39E5E181 89EF0000
2C0F0001 40820010
3C60FF00 6063BE0C
3C001900 2C0F0002
40820010 3C60FF00
60638DD5 3C002E00
2C0F0003 40820010
3C60FF00 6063F7E1
3C008300 2C0F0004
40820010 3C60FF00
60637D77 3C00C800
6000FFFF 94650008
60000000 00000000
*Color 1 of Marth's sword swing is changed on a per costume basis
**Blue costume [default] = Default swing color (teal)
**Red costume = Red swing color
**Green costume = Green swing color
**White costume = Light purple swing color
**Black costume = Gold swing color
$D-Pad Controls Damage [Dan Salvato]
C206D1EC 0000001E
3DE08047 61EF9C3F
8A0F0000 2C100000
41A200D8 3E60805A
62737000 3A400000
2C100001 4082000C
3E40FFFF 3E80BF80
2C100002 4082000C
3E400001 3E803F80
2C100004 4082000C
3E40FFF6 3E80C120
2C100008 4082000C
3E40000A 3E804120
92530000 92930008
3E000000 9A0F0000
3E200000 3DE08045
61EF30E0 820F0000
7E109214 2C100000
40800008 3A000000
920F0000 39EF0E90
3A310001 2C110004
4180FFDC 3DE080BD
61EFA4A0 81EF0000
3E000000 C0130008
C02F1890 EC21002A
C0130004 FC010000
4080000C D00F1890
48000008 D02F1890
81EF0008 2C0F0000
41820008 4BFFFFCC
7C0802A6 00000000
$Turn White During Shield Stun [Dan Salvato]
C206B80C 00000009
7F03C378 81C30070
2C0E00B5 40820034
3DC0C200 91C30518
91C3051C 91C30520
91C30524 39E00000
91E30528 91E3052C
91E30530 91E30534
39E00091 99E30564
8001007C 00000000
$Rolling Results in Immediate Death [Dan Salvato]
04099244 4803A985
$Enable Taunt Cancelling [Dan Salvato]
040DEE70 4BFA5411
040CA4CC 40820058
*Do not use with Taunt Battle
$Stock Control/Crew Battle [Jorgasms]
04036bb4 60000000
C2266678 00000015
3DC0803F 61CEA3E6
89CE0000 2C0E0000
4182008C 3DC08045
39CE310E 3DE08048
39EF0828 3E008045
6210BF14 8A100000
2C100009 40810008
3A000009 8A2E0000
2C110000 4182000C
9A2F0000 48000008
9A0F0000 8A2E0E90
2C110000 4182000C
9A2F0024 48000008
9A0F0024 8A2E1D20
2C110000 4182000C
9A2F0048 48000008
9A0F0048 8A2E2BB0
2C110000 4182000C
9A2F006C 48000008
9A0F006C 3803FFFF
60000000 00000000
C21A57DC 00000005
3E008048 621006E0
3A200009 9A300000
9A300024 9A300048
9A30006C 38BEFFF8
60000000 00000000
C2230D54 00000006
88030005 3DC0803F
61CEA3E6 3DE08045
61EFBF15 3A000001
89CE0000 2C0E00FF
4082000C 9A0F0000
38000001 00000000
C222F76C 00000008
881C0004 3DC0803F
61CEA3E6 3E008045
6210BF15 8A300000
2C110001 40820014
38000002 39E000FF
99EE0000 4800000C
39E00000 99EE0000
60000000 00000000
C222F6BC 00000008
881C0004 3DC0803F
61CEA3E6 3E008045
6210BF15 8A300000
2C110001 40820014
38000002 39E000FF
99EE0000 4800000C
39E00000 99EE0000
60000000 00000000
C2033CC4 0000000A
3DC08045 61CEBF15
89CE0000 2C0E0002
40820038 3DC08045
39CE310E 3DE08048
39EF0828 8A4F0000
9A4E0000 8A4F0024
9A4E0E90 8A4F0048
9A4E1D20 8A4F006C
9A4E2BB0 48000008
98A3008E 00000000
**Essentially, the hack gets rid of damage modifier for handicap
*and replaces it with controllable stocks so that one player can
*spawn with say 6 stocks and another can spawn with 4.
**When handicap is set to "ON" you can set custom stocks
*per player (1 stock - 9 stocks).
**When handicap is set to "AUTO" you can set custom stocks
*per player (1 stock - 9 stocks) just like when handicap is "ON."
*However, upon re-entering the character select screen,
*your handicap will be set to the amount of stocks you had at the end of the game.
*If you had zero stocks (as in you lost), the game will set your stock
*to the current stock setting (any stock amount higher than nine will be set nine).
*This allows for easy crew battles.
*You can still change the stocks manually if needed (rage quits etc.)
$Taunt Battle (r2) [Dan Salvato]
C2261BE0 00000005
3E208045 6231BF12
8A310000 2C110003
40820010 2C040001
40820008 38840001
9899000A 00000000
C22617CC 00000005
3E208045 6231BF12
8A310000 2C110003
4082000C 38000001
48000008 540007FE
60000000 00000000
C2167C08 00000005
3E208045 6231BF12
8A310000 2C110003
4082000C 38000000
48000008 881E0002
60000000 00000000
C2167F70 00000005
3E208045 6231BF12
8A310000 2C110003
4082000C 38000001
48000008 881E000B
60000000 00000000
C2167F7C 00000005
3E208045 6231BF12
8A310000 2C110003
4082000C 38000000
48000008 881E0002
60000000 00000000
C20DED14 0000000D
3E208045 6231BF12
8A310000 2C110003
40820050 887E067B
809E008C 80BE0020
7C042800 40820008
48000018 2C030000
4082000C 38600002
48000008 38600000
3CC0803C 60C66630
2C030000 41820008
38C60004 80E60000
38E70001 90E60000
7FE3FB78 00000000
C20DEBD0 00000003
8063008C 907E0020
7FC3F378 7C0802A6
60000000 00000000
C2165A64 0000000E
3E208045 6231BF12
8A310000 2C110003
40820054 3E20803C
62316630 3E4080BD
6252A4A0 82520000
7F53D378 2C130000
41820010 3A73FFFF
82520008 4BFFFFF0
8A72067B 2C130000
41820008 3A310004
80110000 3E208016
62315AA4 7E2903A6
4E800420 7C0601D6
60000000 00000000
C2036D70 00000003
3BE00000 3C60803C
60636630 93E30000
93E30004 00000000
C20DED40 00000013
7C7F1B78 3E208045
6231BF12 8A310000
2C110003 4082007C
887F067B 809F008C
80BF0020 7C042800
40820008 48000018
2C030000 4082000C
38600001 48000008
38600000 2C030002
40820008 38600001
5463103A 38630518
38800000 909F0518
909F051C 909F0520
909F0528 909F052C
909F0530 909F0534
3C804344 909F0524
38800091 989F0564
3C80437F 7C9F192E
7FE3FB78 00000000
C20D50CC 00000005
3E208045 6231BF12
8A310000 2C110003
4082000C 38000096
48000008 800505D0
60000000 00000000
C216C348 00000008
3FC08045 63DEBF14
881E0000 3FE0803C
63FF6630 83BF0000
7C1D0000 40800018
83BF0004 7C1D0000
4080000C 38600000
48000008 38600002
BB610024 00000000
2845bf12 00FF0300
004807c8 00000001
$Target Test Never Ends [donny2112]
041C4344 38030000
*Match does not end after all the targets have been hit.
$Input Delay Tester [Dan Salvato]
C2390CFC 00000021
3C608047 60639C3C
80630000 3C80805A
60847D00 3CA080BD
60A5A4A0 80050000
2C000000 418200DC
80A50000 546007BD
408200B4 54600739
408200B8 80040000
2C000000 418200BC
38C00000 90C50564
80E40004 2C070000
41820054 48000004
5460077B 40820008
48000024 7CE83B78
2C080014 41800008
39000000 3CC08045
60C630E0 B1060000
48000004 38E70001
2C07001E 4080000C
90E40004 48000064
38E00000 90E40004
48000058 3CC0437F
90C50518 90C50524
38C00000 90C5051C
90C50520 90C50528
90C5052C 90C50530
90C50534 3CC08000
60C60091 90C50564
4BFFFF80 38000001
90040000 4BFFFF5C
38000000 90040000
90040004 48000004
7C0802A6 00000000
*This code tests the input delay of your setup.
*Plug into P1 and start a match. Press D-pad Right
*to enable and D-pad Up to disable. While enabled,
*your character will flash red at a rate of 120bpm.
*Tap D-pad Down at the exact moment your character flashes red.
*Each time you do so, your character's percent damage
*will change to reveal the number of frames between the
*red flash and your input. This is the approximate number
*of frames of input delay your TV has. Note that your human
*timing has a margin of error, so this will only give a rough
*estimate of your TV's input delay.
$Proper 16:9 Widescreen Support [Dan Salvato, mirrorbender]
C2021ABC 00000002
39C00001 38600006
60000000 00000000
C236A4A8 00000007
C03F0034 2C0E0001
41820024 3C004080
90010030 3C004040
90010034 C0010030
EC210032 C0010034
EC210024 39C00000
281E0000 00000000
$PAL Stock Icons [Achilles]
C22F9A28 00000004
3C003F59 6000999A
901D002C 901D0030
3C00C1B0 60000000
60000000 00000000
*Use the smaller PAL stock icons
$L Cancel % in Results Screen [Wooggle]
C208D600 00000009
8A830678 3DC08000
61CE45D4 1EB40008
7DCEAA14 81EE0000
39EF0001 91EE0000
3A0EFFFC 82300000
7E717BD6 3E408045
62523DA4 1EB40E90
7E52AA14 92720000
3880FFFF 00000000
C208D6A4 00000009
8A830678 3DC08000
61CE45D4 1EB40008
7DCEAA14 81EE0000
3A0EFFFC 82300000
3A310064 92300000
7E717BD6 3E408045
62523DA4 1EB40E90
7E52AA14 92720000
EC010024 00000000
04040BBC 60000000
20C61DB8 16200D20
06C61DB8 00000014
1620151A 200C2024
20312026 2028202F
1A210300 00000000
020045D0 000F0000
E2000001 00000000
$Disable Rumble
043D4A70 00000000
[Gecko_Enabled]
$Netplay Community Settings
$Unlock All Characters and Stages
$Boot to Character Select Screen
$Press Y to toggle frozen stages```

**Comment by someone2639** [comment]
Update: I just rebuilt Dolphin and it seems to work now
