### ISSUE TITLE
Issue with running in WSL

### ISSUE THREAD

**Issue by bfaifoefum** [altf4/SmashBot#141]
Is it possible to run SmashBot using WSL? No matter what path I use according to the instructions on the page I keep receiving an error

```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    console = melee.Console(path="/SlippiOnline/")
  File "/home/andrew/.local/lib/python3.8/site-packages/melee/console.py", line 97, in __init__
    _copytree_safe(self._get_dolphin_home_path(), temp_dir)
  File "/home/andrew/.local/lib/python3.8/site-packages/melee/console.py", line 50, in _copytree_safe
    shutil.copytree(src, dst, ignore=_ignore_fifos)
  File "/usr/lib/python3.8/shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/andrew/.config/SlippiOnline/'
```

since it's looking for a file in the home directory which is on Linux systems, will I be able to run it on my Windows machine with WSL?

Let me know if there's any more information I could provide.

If it helps, I am currently running "example.py" copied directly from your website, and no matter what I change the path variable to I still keep getting this error. The only time I do NOT get this error is when my example.py looks like the following:

```
import melee

console = melee.Console(path="/mnt/c/Users/Andrew/Desktop/newenv/FM-Slippi")

controller = melee.Controller(console=console, port=1)
controller_human = melee.Controller(console=console,
                                    port=2,
                                    type=melee.ControllerType.GCN_ADAPTER)

console.run()
console.connect()

controller.connect()
controller_human.connect()

while True:
    gamestate = console.step()
    # Press buttons on your controller based on the GameState here!
```

Doing so gives me the following error:
```
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    console.run()
  File "/home/andrew/.local/lib/python3.8/site-packages/melee/console.py", line 259, in run
    self._process = subprocess.Popen(command, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child     
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Andrew/Desktop/newenv/FM-Slippi/dolphin-emu'
```
However, something to note about this case is that my path is pointing to a Windows download of Slippi, not the Linux version which I used AppImage to extract. When my path points to the Linux version, I get the same error as the first case.

Thanks!

**Comment by altf4** [comment]
WSL may or may not work, but I definitely don't want to officially support it, sorry.
